name: foodstorm
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:

  cloud_firestore:

  firebase_core:

  flutter:  
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.6
  hive: ^2.2.3
  http: ^0.13.4  
  intl: ^0.17.0
  sizer: ^2.0.15
  provider: ^6.0.2
  geolocator: ^8.2.0
  flutter_svg: ^1.0.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5
  path_provider: ^2.0.9
  hive_generator: ^2.0.0 
  adaptive_theme: ^2.3.1
  cupertino_icons: ^1.0.2 
  google_maps_flutter: ^2.1.3
  flutter_native_splash: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_polyline_points: ^1.0.0  
 
  animated_splash_screen: 
     git: https://github.com/clean-code-dev/animated_splash_screen.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.3.2
  flutter_lints: ^1.0.0
    
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"

flutter: 

  uses-material-design: true

  assets:
    - assets/image/
    - assets/cards.json

  fonts:
   - family:  StormIcons
     fonts:
     - asset: fonts/icons/StormIcons.ttf
     
   - family: Gilroy
     fonts:
     - asset: fonts/Gilroy-Light.otf
     - asset: fonts/Gilroy-ExtraBold.otf
       weight: 700

   - family: Humnst777 BlkCn BT
     fonts:
     - asset: fonts/h.ttf

   - family: SFProDisplay-Thin
     fonts:
     - asset: fonts/SFProDisplay-Thin.ttf

   - family: SFProDisplay-Light
     fonts:
     - asset: fonts/SFProDisplay-Light.ttf 

   - family: SFProDisplay-Regular
     fonts:
     - asset: fonts/SFProDisplay-Regular.ttf

   - family: SFProDisplay-Medium
     fonts:
     - asset: fonts/SFProDisplay-Medium.ttf 

   - family: SFProDisplay-Semibold
     fonts:
     - asset: fonts/SFProDisplay-Semibold.ttf 

   - family: SFProDisplay-Bold
     fonts:
     - asset: fonts/SFProDisplay-Bold.ttf

flutter_intl:
  enabled: true

